<?php  $lastModify=\App\DataBanksIntraday::orderBy('id', 'desc')->first()->lm_date_time->format('c'); echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      <url>
         <loc>{{url('/market-composition')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/market-frame')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/monitor')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/data-matrix')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/watch-matrix')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/price-matrix')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/dse-price-list')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/news/search')}}</loc>
      </url>
      <url>
         <loc>{{url('/collective/news')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/sector-minute-chart')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/sector-pe')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/category-pe')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/dividend-yield-payout-ratio')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/dividend-yield-payout-ratio')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/technical-analysis')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/technical-analysis/basic-technical-analysis')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/technical-analysis/executive-technical-analysis')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/technical-analysis/advance-technical-analysis-course')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/technical-analysis/advance-usage-of-amibroker')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/technical-analysis/free-technical-analysis-course')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/fundamental-analysis/basic-fundamental-analysis')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/fundamental-analysis/business-and-financial-modeling')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/fundamental-analysis/risk-management')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/fundamental-analysis/standard-financial-reporting-with-useful-tips')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/courses/upcoming-courses')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/ipos')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/ipos/history')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/ipos/results')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/contests')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/mycontests')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/blog')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/tutorials/technical')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/resources/amibroker-data-plugin-dse')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/download')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/market-depth')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{url('/dse/stock/candlestick-pattern')}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>

      @foreach(\App\Screener::all() as $screener)
         <url>
            <loc>{{url('/screeners/'.$screener->slug)}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
         </url>      
      @endforeach

   @foreach(\App\Instrument::whereNotIn('sector_list_id', [22, 24, 5, 4])->where('active','1')->get() as $instrument)
      <url>
         <loc>{{route("ta-chart-new", ['instrument' => $instrument->instrument_code, 'name' => str_slug($instrument->name)])}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{route("advance-ta-chart", ['instrument' => $instrument->instrument_code, 'name' => str_slug($instrument->name)])}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{route("minute-chart", ['instrument' => $instrument->instrument_code, 'name' => str_slug($instrument->name)])}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{route("news-chart", ['instrument' => $instrument->instrument_code, 'name' => str_slug($instrument->name)])}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
      <url>
         <loc>{{route("fundamental-details", ['instrument' => $instrument->instrument_code, 'name' => str_slug($instrument->name)])}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
   	<url>
         <loc>{{route("trade-details", ['instrument' => $instrument->instrument_code, 'name' => str_slug($instrument->name)])}}</loc>
         <lastmod>{{$lastModify}}</lastmod>
      </url>
   @endforeach
</urlset> 